(function () {
  "use strict";
  var MASK_W = 720, MASK_H = 360, MASK_B64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHC////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////5+AAAAAD/P/////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf7//////8ADc/D5//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////8H3/f//////v/8/AH4AAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwf7/+//+fgD////////////8//+AAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8Hf7z///gP/////////////v//gAAAAAAAAAAAAAAAAAAACsgZ998AAAAAAAABf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//2fP///8H///////////////74AAAAAAAAAAAPVwADgAAADwHrQAAAAAAAAAAHf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABg///f9//7gAP//////////////7gAAAAAAAAH9fcf+AAAAAAAAAAAAAAAAAAAAABvvwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAf/9//8AAAf//////////////8AAAAAAAAAC/vgDAAAAAAAAAAAAAAAAAAAAAAAH/hQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8cC/+/v//gD////////////////EAAAAAAAAAF/f/gAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAePgO5///+D////////////////+EAAAAAAAAAAMfxwAAAAAAAAAAAAAAAAAAAAAAAAAP8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPwCBwA+ADz//AAH///////////////94gAAAAAAAAAEPg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAABgAAABA/9wAAA////////////////6AAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD7xgGAAID+B////AAD///////////////7gAAAAAAAAAAAMAAAAAAAAAAAAAAAA/AAAAAAAABAD/8AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwPQPAO34S/wAAwAAA/av/////////////iAAAAAAAAAAAAAAAAAAAAAAAAAANf+AAAAAAAABgf///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEM/+D+EvwAPwAvAAAAAAAP////////////4AAAAAAAAAAAAAAAAAAAAAAAAAH/4AAAAAAAAB//////7AAAAAAAT+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///8YDw+f///4AAAAAAH////////////LAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAH///////+AAAAAAAD//x6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAQOPn/vgAAAAAAA////////////wAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAAAI////////wAAAAAAAAYAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/GAAAAAAAAAAAAAAAAAAAAP///////////oAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAB///////8cAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAABAO8f+B8AgAAAAAAAP/////////6/gAAAAAAAAAAAAAAAAAAAAAAAB/wAAAAAAAAH///////miAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//nAArgHwf4Pz/f4AAAAAAH/////////ngAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAOAAB////////wf//4Af+AAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/5+eM+Bn+Ywfn/kQAAAAAAP/////////t0AAAAAAAAAAAAAAAAAAAAAAAAH4AAAA/ggI////////////////gAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/j//+/AP+MA/n+ffAAAAAAD//////////MAAAAAAAAAAAAAAAAAAAAAAAAH4AAAB/wg8P///////////////gAAP//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAH+P///fgB8aA/3//doAAAAAPP/////////wAAAAAAAAAAAAAAAAAAAAAAAAf4AAAB/nP/l///////////////gQAD//8AAAAAAAAAA+AAAAAADAAAAAAAAAABgA////gAB/AP/////wAAAAAv////////58AAAAAAAAAAAAAAAAAAAAAAAAF8AAAP/Hg/7///////////////g//////8AAAAAAAADAAAAAAD//gAAAAAAAAAAD////wAB/gP////+1AAAABx////////48AAAAAAAAAAAAAAGaWAAAAAAAAfgAAH/z//9///////////////9/////////gAAAAAAAAAAAA////8AAAAAAMAAAH3///gB/4Cf/9//uQAAABv///////+OAAAAAAAAAAAAAAGN//gAAAAAAAAGAAP/j//z/////////////////////////wAAAAAAAAAAAD//////+AAA7+I4A////+wYfgAHgYP//0AAAD9f////////gAAAAAAAAAAAAAb//+3AAAAAAAABsAP/n////////////////////////////wAB7/+AAAAAAH///////+D/////wA//3/BfF8QH6CR//+AAAAA////////6AAAAAAAAAAAAAD3////YAAAAcAAAf8D/jv//////////////////////////////g//+wAAAD////////////////8f8OAgPB+cF/AEf/gAAAAB////////gAAAAAAAAAAAAB5//////4AAAQDAef/w/x5//////////////////////////////////+AAAD/////////////////CDHgAeD+4v8AHD/5AAAAN//////0AAAAAAAAAAAAAAEH//////+ADwB8v///9/x+///////////////////////////////////4AAAf///////////////+h4/+vTf/8f+AfB//oAAAS//////AAAAAAAAAAAAAAAQf///////4DwP///////w9///////////////////////////////////8AAAP//////////////////f///v/+/+AIA//4AAAv/////+AAAAAAAAAAAAAAABf///////8DA////////D////////////////////////////////////++AAB//////////////////f///////8AAD///4AAP/////8AAAAAAAAAAAAAAAH/////+P/8B////////6P///////////////////////////////////v//wDwP////////////////////////ywAAP/1/wAAf/////wAAAMAHAAAAAAAAA7//////wPw7/////////////////////////////////////////////n/+gf/////////////////////////PuAAAH/wfgAAPf///7AAAAOf/AAAAAAAAAf//8f//4AH//////////////////////////////////////////////gP8AH//////////////////////////NAAe//8HAAAD///8AAAAAH//4AAAAAAAAf//gH//4AP//////////////////////////////////////////////AB0AH/P///////////////////////+f4A////gAAACP//wAAAAAn//wAAAAAAAD///gf//8cP////////////////////////////////////////////6cAAAAAAP///////////////////////8f+AID//oAAAA///oAAAAAD/+AAAAAAAAP///A////D//////////////////////////////////////////////4AAAAAAP//////////////////////vA/HwAC//wAAAB///4AAAAAA/gAAAAAAABf//+H///////////////////////////////////////////////////8AAAeAB///////////////////////+AGABgAfz4AAAA///gAAAAAAAAAAAAAAAB///wP///////////////////////////////////////////////////8AAAAA////////////////////////gAAcAAAB8QAAAAf//AAAAAAAAAAAAAAAAP///A////////////////////////////////////////////////////+AAAAB////////////////////////AAAQI/cAfAAAAAH/+AAAAAAAAAAAAAAAB///+Af//////////////////////////////////////////////z///8AAAAAD///////////////////////+AAAAI//AAQAAAAH/+AAAAAAAAAAAAAAAD///+Af////////////////////////////////////////////4Xz///AAAAAAB////+9/////////////////8AAAAA//gAAAAAAB/+AAAAAAAAAAAAAAAD///8Af////////////////////////////////////////////gOD//8AAAAAAAn////8f////////////////4AAAAAf/+AAAAAAAJ8AAAAAAAAAAAAAAAB///+Af////////////////////////////////////////////AMP//gAAAAAAOf///n8B////////////////4AAAAAf/+QIAAAAAB4AAAAAAAAAAAAAEAD////mf8D/////////////////////////////////////////8AA/kCAAAAAAAAA///PAAA3//////////////wAAAAAf/+AYAAAAAAAAAAAAAAAAAAAAAAD////wAAH/////////////////////////////////////////wAD4AAAAAAAAAAA//8MAAAD//////////////wAAAAA///AeAAAAAAAAAAAAAAAAAAAAAAC////gB///////////////////////////////////////4CED8APwAAAAAAAAAAApb+AAAAA///////////////AAAAB//9h/AAAAAAAAAAAAAAAAAAAAAAB/j/+AA///////////////////////////////////////wAAAAAfkAAAAAAAAAAAAH8wAAAAD//////////////AAAAA///v/AAAAAAAAAAAAAAAAAACOAAAeB/4AIf/////////////////////////////////////+AAAAAB/AAAAAAAAAAAAAHjgAAAACX/////////////gAAAAP////4AAAAAAAAAAAAAAAAAA8AAAAA/4QAf/////////////////////////////////////8AAAAAP/4AAAAAAAAAAAAeHAAAAADX/////////////iAAAAP////wAAAAAAAAAAAAAAAAAF/wAAAY/4gcf/////////////////////////////////////wAAAAAP/wAAAAAAAAAAAA4AAAAAAB5//////////////4AAAH////wAAAAAAAAAAAAAAAAAA/gAAB4f8A///////////////////////////////////////gAAAAA//wAAAAAAAAAAAHgAAAAAAA1//////////////8AAGH////4AAAAAAAAAAAAAAAAAAfgAAD8PwA///////////////////////////////////////AAAAAA//4AAAAAAAAAAA0AAAAAAAAHX//////////////gAAP////8AAAAAAAAAAAAAAAAABPwAAD5sAA//////////////////////////////////////8AAAAAB//AAAAAAAAAAADIAAAAAAAAG///////////////9AA//////wAAAAAAAAAAAAAAAAEP4AAB/hAAf/////////////////////////////////////wAAAAAB//AAAAAAAAAAAcAAAAAAAAADH///////////////8H//////8AAAAAAAAAAAAAAAAfh4AABzABj//////////////////////////////////////BAAAAAB//AAAAAAAAAAAAAAAAAAAAAAH///////////////4H//////8AAAAAAAAAAAAAAAD/B+AAA8wP///////////////////////////////////////8UEAAAA/wAAAAAAAAAAMAAAAAAAAAACH///////////////8D//////PAAAAAAAAAAAAAAAD+A/AAB//////////////////////////////////////////+eAAAAA/wAAAAAAAAABAAAAAAAAAAABB///////////////8D/////9/4AAAAAAAAAAAAAAD/H/gB/////////////////////////////////////////////sAAAA/wAAAAAAAAAAAAAAAAAAAAAAB///////////////8j///////wAAAAAAAAAAAAAAB/D/4H/////////////////////////////////////////////OAAAA+AAAAAAAAAAAAAAAAAAAAAAAAH//////////////+B///////wAAAAAAAAAAAAAAH+D/4H/////////////////////////////////////////////8AAAAeAAAAAAABgAAAAAAAAAAAAAAAP///////////////n///////gAAAAAAAAAAAAAADgP/wH/////////////////////////////////////////////OAAAAcAAAAAAAAAAAAAAAAAAAAAAAAP///////////////3//////4wAAAAAAAAAAAAAAAAA/4/////////////////////////////////////////////+OAAAAYAAAAAAAAAAAAAAAAAAAAAAAAZ//////////////////////wwAAAAAAAAAAAAAAAAH4n/////////////////////////////////////////////+OAAAAgAAAAAAAAAAAAAAAAAAAAAAAAP////////////////////BfBgAAAAAAAAAAAAAAAASAH/////////////////////////////////////////////+PAAADAAAAAAAAAAAAAAAAAAAAAAAAADz//////////////////8HADQAAAAAAAAAAAAAAAAAAf/////////////////////////////////////////////+PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd//////////////////wAwD/gAAAAAAAAAAAAAAAAX//////////////////////////////////////////////+MgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPf/////////////////P4AH/AAAAAAAAAAAAAAAABH//////////////////////////////////////////////8MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE/////////////////+/wAP/gAAAAAAAAAAAAAAAH///////////////////////////////////////////////8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHf////////////////9/wAf/YAAAAAAAAAAAAAAAB///////////////////////////////////////////////wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////7/wAAEwAAAAAAAAAAAAAAAAf//////////////////////////////////////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////0CAAQAAAAAAAAAAAAAAAAP////////////h/////////////////////////////////gOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////////////5nAAAAAAAAAAAAAAAAAAAD//////////j8B/////////////////////////////////AoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////+nAAAAAAAAAAAAAAAAAAAD//////////A8D////////////////////////////////+AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////j8AAAAAAAAAAAAAAAAAAAB////H////+A/v////////////////////////////////8AYAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////////8fAAAAAAAAAAAAAAAAAAAAH////A////8AYH////////////////////////////////4AMAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////////A8AAAAAAAAAAAAAAAAAAAAH//+fg////4AAA////////////////////////////////wAeIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////+AwAAAAAAAAAAAAAAAAAAAAH//4Hwf///4AAAf///////////////////////////////gAfxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////////4AAAAAAAAAAAAAAAAAAAA////hgH8D///wAAAH//////////////////////////////+AAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////////wAAAAAAAAAAAAAAAAAAAA////AAL8A///wAAAB/////////////////////////////+IAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////////wAAAAAAAAAAAAAAAAAAAAf///gBh+AP//wAAAB/////////////////////////////4AACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////4AAAAAAAAAAAAAAAAAAAA////ABg/wH//wB8AB/////////////////////////////wAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////8AAAAAAAAAAAAAAAAAAAAAf//8AAAH4H//8H/wD/////////////////////////////gAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////8AAAAAAAAAAAAAAAAAAAAAf//wADgB+H+Tg//////////////////////////////z//gAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////////wAAAAAAAAAAAAAAAAAAAAA///gABgA8n4h///////////////////////////////j/+AAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////wAAAAAAAAAAAAAAAAAAAAA///BABgAIH8D//////////////////////////////+Hj4AAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////6gAAAAAAAAAAAAAAAAAAAAB//+AABgAMB+D//////////////////////////////8EB4AAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////////////AAAAAAAAAAAAAAABAAAAAB///AAAAAIA8A//////////////////////////////gAD8AAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////7AAAAAAAAAAAAAAAAAAAAAA//+AAAAAYATh//////////////////////////////wAD+AAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////////////6AAAAAAAAAAAAAAAAEAAAAA//8AAAAfABcBf/////////////////////////////8QAfAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////////////4AAAAAAAAAAAAAAAAAAAAAA//wAAAQHAAcAf/////////////////////////////8+AfgAEfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////8AAAAAAAAAAAAAAAAAAAAAAB/gA9/8BAAAAPn6////////////////////////////4A/gAH+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////8AAAAAAAAAAAAAAAAAAAAAAAgAf//4AAAAABBw////////////////////////////gAfgIP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////////+AAAAAAAAAAAAAAAAAAAAAAAgB///8AAAAAAAA////////////////////////////AAfgAv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////4AAAAAAAAAAAAAAAAAAAAAAAyH///8AAAB6AAw///////////////////////////+AAfAf/yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////////////wAAAAAAAAAAAAAAAAAAAAAAB/////+AAAAAABg///////////////////////////+AAcA+5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////////AAAAAAAAAAAAAAAAAAAAAAAB/////wAAAAAAAB////////////////////////////gAAjX4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////8AAAAAAAAAAAAAAAAAAAAAAAH/////8AAAAAAAB////////////////////////////gAAUeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////////8AAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAD////////////////////////////wAgeYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////////wAAAAAAAAAAAAAAAAAAAAAAA///////8AA4AAAD////////////////////////////wABPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////gAAAAAAAAAAAAAAAAAAAAAAB////////gD8AAAD////////////////////////////4AAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////////AAAAAAAAAAAAAAAAAAAAAAAB////////gD/wAAH////////////////////////////8AAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcf/////////+AAAAAAAAAAAAAAAAAAAAAAAD////////wD//g8P////////////////////////////4AAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOP/////////+AAAAAAAAAAAAAAAAAAAAAAAD/////////D/////////////////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOP//////+iH+AAAAAAAAAAAAAAAAAAAAAAAB///////////////////////////////////////////qAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHH/////2/gEfAAAAAAAAAAAAAAAAAAAAAAAD///////////////////h///////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz/////wHQAPAAAAAAAAAAAAAAAAAAAAAAAH/////////////+7////B///////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABz/////gAAAHgAAAAAAAAAAAAAAAAAAAAgAP//////////////7////g///////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEx////8AAAAPgAAAAAAAAAAAAAAAAAAAAIAf//////////////f////gf//////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4f///4AAAAPgAAAAAAAAAAAAAAAAAAAAAD///////////////p////wP//////////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8f///4AAAAHwAAAAAAAAAAAAAAAAAAAAAH///////////////w////4D//////////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOP///4AAAADwAAAAAAAAAAAAAAAAAAAAAH///////////////w////8B0/////////////////////AACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGD///4AAAADwAAAAAAAAAAAAAAAAAAAAAf///////////////wf///8AA////////////////////+AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH///8AAAAB0AAAAAAAAAAAAAAAAAAAAAf///////////////4f///8gCf///////////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADB///wAAAAAgAAAAAAAAAAAAAAAAAAAAA////////////////8P///+gGAPgf////////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg///4AAAAABEAAAAAAAAAAAAAAAAAAAA////////////////8P////geAAAP////////////////8MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwf//wAAAAAAgAAAAAAAAAAAAAAAAAAAB////////////////+H////wfAAAH////////////////wYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYP//4AAAAAAgAAAAAAAAAAAAAAAAAAAD////////////////+B//////wAAD////////////////g4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIH//wAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////+B//////8AAB////////////////A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAA/4AQAAAAAAAAAAAAAAAAAAH/////////////////A//////+AAAH//////v//////+wAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//wAAABj+CAAAAAAAAAAAAAAAAAAAH/////////////////g///////AAA///////z//////+gAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//4AAAAIPgAgAAAAAAAAAAAAAAAAAP/////////////////w//////+AAAff////+D//////oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AA/gAB4AAAAAAAAAAAAAAAAAAAP/////////////////w//////8AAAPf////AD////+CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAB//8AB/AAB8AAAAAAAAAAAAAAAAAAAH/////////////////4f/////4AAAEP////AB////4CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//8AB+AAAfwAAAAAAAAAAAAAAAAAAD/////////////////wP/////0AAAAf///+AA////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAB//+AB+AAIAHYAAAAAAAAAAAAAAAAAH/////////////////4D/////gAAAAf///4AAf///wHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAA///AD+AAAAD/AAAAAAAAAAAAAAAAAH/////////////////4D/////gAAAAP///wAAP///weAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AH+AAAAB/gAAAAAAAAAAAAAAAAD/////////////////4D/////AAAAAP///gAAf///geAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//7/8AAB4P0jgAAAAAAAAAAAAAAAD/////////////////+B////+AAAAAP///AAAH///wAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///8AAAQAAAIAAAAAAAAAAAAAAAD/////////////////+A////4AAAAAP//+AAAH///4AAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///4AAAAAAAAAAAAAAAAAAAAAAAD//////////////////Af///4AAAAAP//4AAAH///8AAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///4AAAAAAAAAAAAAAAAAAAACAAH//////////////////Af//+AAAAAAH//4AAAH///+AAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//4AAAAAAAAMAAAAAAAAAAAAAAH//////////////////AP//4AAAAAAH//AAAAPH///AAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADB/7/AAAAAAAAAAAAAAAAAAAAAAH//////////////////gf//wAAAAAAH/+AAAAAH///gAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///AAAAAAAAAAAAAAAAAAAAwAP//////////////////gf//gAAAAAAD/8AAAAAH///wAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAAAAAAAAAAAAf//////////////////4P/4AAAAAAAD/8AAAAAD///wAAA6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wAAAAAAAAAAAAAAAAAAAAAP//////////////////+P/wAAAAAAAB/8AAAAAD///wAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAAAAAAAAAAAAAAAAAAH///////////////////X+AAAAAAAAB/8AAAAAD///wAAAqYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN/gAAAAAAEAAAAAAAAAAAAAAP///////////////////vgAAAAAAAAB/+AAAAABz//4AAAYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAAP///////////////////2AAAAAAAAAA/8AAABABz//4AAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAwAAAAAAAAAAAAAAAAAD///////////////////4AAAAAAAAAA/8AAABABwf/wAAAImAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgAABgAAAAAAAAAAAAAAAAAB///////////////////wABgAAAAAAAf8AAABAAwP/wAAACCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAPHgAAAAAAAAAAAAAAAAH///////////////////4AfAAAAAAAAP8AAAAACgP/wAAADWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAB//gAkAAAAAAAAAAAAAAA///////////////////8f/AAAAAAAAP8AAAAABgP/AAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAB/f/HkAAAAAAAAAAAAAAAf/////////////////////AAAAAAAAP4AAAAABAB4AAACAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAB/P//4AAAAAAAAAAAAAAAH/////////////////////AAAAAAAAHyAAAAABAA4AAAEBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8PD/P//8AAAAAAAAAAAAAAAH////////////////////+AAAAAAAAHzAAAAABQAwAAAIAhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfxn////+AAAAAAAAAAAAAAAD////////////////////+AAAAAAAAHDAAAAABwAgAAAQADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADh//////gAAAAAAAAAAAAAAD////////////////////8AAAAAAAADHgAAAAB4AAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABx//////wAAAAAAAAAAAAAAD////////////////////8AAAAAAAAADgAAAAA4AAAAAAD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg//////4AAAAAAAAAAAAAAA////////////////////4AAAAAAAAADwAAAAAYAAAAAgCOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAf///////////////////wAAAAAAAAADwAAAAAOAAAABAAOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAAAAAAAAH///8H//////////////wAAAAAAAAADgAAAAAPAAAABgAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////AAAAAAAAAAAAAAD///AD//////////////wAAAAAAAAAAAAAAAAHgAAAD4ACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////wAAAAAAAAAAAAAB//8AB//////////////gAAAAAAAAAAAAAADwHwAAAH+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////8AAAAAAAAAAAAAAeAAAB//////////////AAAAAAAAAAAAAAAB8H4AAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////+AAAAAAAAAAAAAAAAAAAA/////////////AAAAAAAAAAAAAAAA8H4AAA/wAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////AAAAAAAAAAAAAAAAAAABf///////////+AAAAAAAAAAAAAAAAfD4AgB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////AAAAAAAAAAAAAAAAAAAAP///////////8AAAAAAAAAAAAAAAAPh4IAD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////AAAAAAAAAAAAAAAAAAAAP///////////4AAAAAAAAAAAAAAABHx4AAf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////gAAAAAAAAAAAAAAAAAAAP///////////gAAAAAAAAAAAAAAAAD88AA//wAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAAAAAAf///////////AAAAAAAAAAAAAAAAAA+MAE//wAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAAAAAAf//////////8AAAAAAAAAAAAAAAAAI/gAP//4AEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////////wAAAAAAAAAAAAAAAAAAAf//////////4AAAAAAAAAAAAAAAAAE/jAf//g/4EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////////4AAAAAAAAAAAAAAAAAAQf//////////wAAAAAAAAAAAAAAAAAA/oAP//gAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAf/////////eAAAAAAAAAAAAAAAAAAAf//////////gAAAAAAAAAAAAAAAAAAP5AP//gCAECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAf/////////+wAAAAAAAAAAAAAAAAAB///////////gAAAAAAAAAAAAAAAAAAP4AP//hEgOB8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////9+AAAAAAAAAAAAAAAAAA///////////AAAAAAAAAAAAAAAAAABH+AD//BuAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////7/gAAAAAAAAAAAAAAAAAf/////////+AAAAAAAAAAAAAAAAAAAn+QD/+B8GAI8PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////gAAAAAAAAAAAAAAAAAf/////////8AAAAAAAAAAAAAAAAAAAT/AD/+D4AAA0H4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////uAAAAAAAAAAAAAAAAAP/////////wAAAAAAAAAAAAAAAAAAAB/5D/+DsAAAuP/gAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////////////AAAAAAAAAAAAAAAAH/////////wAAAAAAAAAAAAAAAAAAAB/wAN+DuA14ff/4AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////gAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAAAAAAA/wAAaBuAQEb///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////wAAAAAAAAAAAAAAAB/////////gAAAAAAAAAAAAAAAAAAAAfwAAABnAAAA///wAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////////////4AAAAAAAAAAAAAAAA/////////AAAAAAAAAAAAAAAAAAAAAHwAAABkAAAAH//4AGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////gAAAAAAAAAAAAAAA/////////AAAAAAAAAAAAAAAAAAAAADwAAABhAAAAB//8AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////wAAAAAAAAAAAAAAA/////////AAAAAAAAAAAAAAAAAAAAAAQAAAAAAAASA//+H4EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////wAAAAAAAAAAAAAAAf////////gAAAAAAAAAAAAAAAAAAAAAPAAAAAAAACAf//hgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////wAAAAAAAAAAAAAAAf////////AAAAAAAAAAAAAAAAAAAAAA/hgAAAAAACAf//AABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////////wAAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAH/8AAAAAAAAf//AAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////////wAAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAAn9gAAAwCAA//PgAARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////wAAAAAAAAAAAAAAAH////////gAAAAAAAAAAAAAAAAAAAAAAA/4QA8AAABz+DwAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////wAAAAAAAAAAAAAAAH////////gAAAAAAAAAAAAAAAAAAAAAAAAC4+DwAAAB+B4AAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////////////gAAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAEA8hAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////////////AAAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAAAAADgcAAAAAAAfQAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////+AAAAAAAAAAAAAAAAH////////wAAAAAAAAAAAAAAAAAAAAAAAAAAgQAAAAAAADgAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////8AAAAAAAAAAAAAAAAH////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////////8AAAAAAAAAAAAAAAAD////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////4AAAAAAAAAAAAAAAAD////////4IAAAAAAAAAAAAAAAAAAAAAAAAAAAAMYAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////wAAAAAAAAAAAAAAAAH////////4AAIAAAAAAAAAAAAAAAAAAAAAAAAAAC/kAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////QAAAAAAAAAAAAAAAAP////////4AAIAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////AAAAAAAAAAAAAAAAAf////////4AAMAAAAAAAAAAAAAAAAAAAAAAAAAAP/wAeAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////AAAAAAAAAAAAAAAAAf////////4AAcAAAAAAAAAAAAAAAAAAAAAAAAAAP/wAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////AAAAAAAAAAAAAAAAAf////////4AA8AAAAAAAAAAAAAAAAAAAAAAAAA4f/0AeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////AAAAAAAAAAAAAAAAAf////////8AB8AAAAAAAAAAAAAAAAAAAAAAAAD8f/gAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////AAAAAAAAAAAAAAAAA/////////4AD+AAAAAAAAAAAAAAAAAAAAAAAAD///wAf4AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////////AAAAAAAAAAAAAAAAA/////////4AH6AAAAAAAAAAAAAAAAAAAAAAAAH///4Af4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////////AAAAAAAAAAAAAAAAA/////////wB/8AAAAAAAAAAAAAAAAAAAAAAAAX///+Af4AAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////AAAAAAAAAAAAAAAAB/////////gB/4AAAAAAAAAAAAAAAAAAAAAAAAf////g/4AAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////////AAAAAAAAAAAAAAAAA////////8AD/4AAAAAAAAAAAAAAAAAAAAAAAD/////w/8AAAAAAAAAAAAAAAAAAAAAQAAgAAAAAAAAAAAAAAAAAAAAAAf//////////AAAAAAAAAAAAAAAAB////////wAD/4AAAAAAAAAAAAAAAAAAAAAAAD///////8AAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////+AAAAAAAAAAAAAAAAA////////wAD/4AAAAAAAAAAAAAAAAAAAAAAAD///////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////8AAAAAAAAAAAAAAAAAf///////gAD/wAAAAAAAAAAAAAAAAAAAAAAAH///////+AAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////+AAAAAAAAAAAAAAAAAf//////+AAB/wAAAAAAAAAAAAAAAAAAAAAAAH////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////8AAAAAAAAAAAAAAAAAP//////4AAB/wAAAAAAAAAAAAAAAAAAAAAAAf////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////8AAAAAAAAAAAAAAAAAP//////4AAB/gAAQAAAAAAAAAAAAAAAAAAAD/////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////4AAAAAAAAAAAAAAAAAH//////8AAD/gAAAAAAAAAAAAAAAAAAAAAB//////////8AAAABCAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAAAAH//////8AAD/gAEAAAAAAAAAAAAAAAAAAAD//////////8AAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAAAAD//////+AAH/AAAAAAAAAAAAAAAAAAAAAAP//////////+AAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////gAAAAAAAAAAAAAAAAAB//////+AAP/AAAAAAAAAAAAAAAAAAAAAAf//////////+AAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////AAAAAAAAAAAAAAAAAAB//////+AAH/AAAAAAAAAAAAAAAAAAAAAB////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////gAAAAAAAAAAAAAAAAAAB//////+AAH+AAAAAAAAAAAAAAAAAAAAAA////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////+AAAAAAAAAAAAAAAAAAAB//////+AAH+AAAAAAAAAAAAAAAAAAAAAB////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////wAAAAAAAAAAAAAAAAAAAB//////+AAH+AAAAAAAAAAAAAAAAAAAAAB////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////gAAAAAAAAAAAAAAAAAAAA//////8AAD8AAAAAAAAAAAAAAAAAAAAAB////////////+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////AAAAAAAAAAAAAAAAAAAAA//////gAABwAAAAAAAAAAAAAAAAAAAAAA////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////+AAAAAAAAAAAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////8AAAAAAAAAAAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAAAAC/////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAAAAB/////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAAAAAAAAAf/////AAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAAAAAAAAAf////+AAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAAAAAAAAAP////+AAAAAAAAAAAAAAAAAAAAAAAAAAAf////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////8AAAAAAAAAAAAAAAAAAAAAH////8AAAAAAAAAAAAAAAAAAAAAAAAAAAf////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////4AAAAAAAAAAAAAAAAAAAAAD////4AAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////wAAAAAAAAAAAAAAAAAAAAAD////wAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+wAAAAAAAAAAAAAAAAAAAAAD////wAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAAAAAAAAAAAAAAAB////gAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAAAAAAA///+AAAAAAAAAAAAAAAAAAAAAAAAAAAAH////A///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAD///4AH/////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAAAAA///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAH//8AAD/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAAAAA///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//wAAB+////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAf/////gAAAAAAAAAAAAAAAAAAAAAAAf/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//gAAA9////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////7/AAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAZ////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////8eAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAARf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///gAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHP///AAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///AAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///AAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//+AAAAAAAAOYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfngAAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf4AAAAAAANcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAD4AAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABX//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAn+gAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv1gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGz4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAt8AAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF/0AAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AAAAAAAAAAAAAAH/gB/gAAAAH8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZ8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT/+AAAAAAAAAAAf/////j/4AAfwP///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/98AAAAAAAB//////////j/////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////AQAAAf////////////////////eAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////wAAP/////////////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AH/////////gAA////////////////////////+8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8D/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8Af/////////gAD//////////////////////////2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAef/gAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAA/8//////////ACf///////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALP/gAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAf////////////Af////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPn/wAAAAAAAAAAAAAAAAABAAAH////wZgf/////////////A///////////////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/3/4AAAAAAAAAAAAAAAAHHAAf/////////////////////+B////////////////////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAB+/z/8AAAAAAAAAAAAAAAAP/////////////////////////+H////////////////////////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+AAAAAAAAXD/+AAAAAAAAAAAAAAAAP///////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAEDAAEMAABgAAH/+AAAAAAAAAAAAAAAD////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAH/8/5/YANjoL//zAAAAAAAAAAAAAAD////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAABgwAAAAADn/////4/z////8AAAAAAAAAAAAAAD////////////////////////////////////////////////////////////4AAAAAAAAAAAAAAAAAAAAAAO+ADDAAAf////////////4AAAAAAAAAAAAAAB////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAQHgAOf///xwAAD///////////+wAAAAAAAAAAAAAA////////////////////////////////////////////////////////////kAAAAAAAAAAAAAAAAAAP////////++B/B///////////8AAAAAAAAAAAAAAD////////////////////////////////////////////////////////////gAAAAAAAAAAAAAAAAA//////////////////////////wAAAAAAAAAAAAAf/////////////////////////////////////////////////////////////gAAAAAAAAAAAAAAAHP/////////////////////+P//gAAAAAAAAAAAAB///////////////////////////////////////////////////////////////gAAAAAAAAAAAAAADYH//////////////////////gAAAAAAAAAAAAAAB////////////////////////////////////////////////////////////////wAAAAAAAAAAAAP+ENP//////////////////////4AAAAAAAAAAAAAA/////////////////////////////////////////////////////////////////4EAAAAAAAAAAAP//f////////////////////////8AAAAAAAAAAAAH/////////////////////////////////////////////////////////////////+AAAAAAAAAAAAAH////////////////////////+AAAAAAAAAH/wAA//////////////////////////////////////////////////////////////////+uAAAAAAAAAAAAf///////////////////////g/AAB4AAAAAP+AAB//////////////////////////////////////////////////////////////////4AAAAAAAAAAP8AAP//////////////////////+cAAeAAAAAAf/4AAA////////////////////////////////////////////////////////////////4AAAAAAAAAAAA/wAAP///////////////////////8AAAAAAAA//8AAAAf//////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAA////////////////////////8AAAAAAAf//wAAAB//////////////////////////////////////////////////////////////+AAAAAAAAAAAAAAAAA////////////////////////+AAAAAAB/wAAAAf////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAD/////////////////////////////4AAAAAAAAP//////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAB/////////////////////////////wAAAAAAB////////////////////////////////////////////////////////////////////gAAAAAAAAAAAAAB/////////////////////////////AAAB//8H////////////////////////////////////////////////////////////////////4AAAAAAAAAAAAAD/////////////////////////////+AA//////////////////////////////////////////////////////////////////////////4AAAAAAAAAAA////////////////////////////////gP///////////////////////////////////////////////////////////////////////////gAAAAAAAAAf//////////////////////////////////////////////////////////////////////////////////////////////////////////////+AAAAAAAAD////////////////////////////////////////////////////////////////////////////////////////////////////////////////+////AAAB/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+AAAAf/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////";
  var PHI0 = 18 * Math.PI / 180, LAM0 = -8 * Math.PI / 180;
  var W = 384;
  var SPIN = 2 * Math.PI;
  var IDLE_RATE = (2 * Math.PI) / 42;
  var PLANET_DEG_PER_SEC = 14;
  var OCEAN_A = 0.14;

  var MASK = (function () {
    var bin = atob(MASK_B64), b = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) b[i] = bin.charCodeAt(i);
    return b;
  })();

  function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }
  function ease(t) { return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2; }
  function landBit(row, col) {
    var idx = row * MASK_W + col;
    return (MASK[idx >> 3] >> (7 - (idx & 7))) & 1;
  }

  function init(node) {
    var canvas = node.querySelector("canvas");
    if (!canvas) return;
    var ctx = canvas.getContext("2d");
    canvas.width = W; canvas.height = W;
    var sc = document.createElement("canvas");
    sc.width = W; sc.height = W;
    var sctx = sc.getContext("2d", { willReadFrequently: true });
    var src = new Uint8ClampedArray(W * W * 4);
    var out = ctx.createImageData(W, W);
    var od = out.data;
    var rhoA = new Float32Array(W * W);
    var kA = new Float32Array(W * W);
    var rowA = new Uint16Array(W * W);
    var colA = new Uint16Array(W * W);
    var base = new Uint8ClampedArray(W * W * 4);
    var ready = false, mode = "rest";
    var angle = 0, angle0 = 0;
    var t = 0, from = 0, to = 0, t0 = 0, dur = 1100, morphRaf = 0;
    var restRaf = 0, restLast = 0;
    var planetRaf = 0, planetLast = 0, planetSpin = 0, planetAcc = 0;
    var autoTimer = 0, visible = true, atm = null;
    var reduced = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    function precompute() {
      var cx = W / 2;
      for (var y = 0; y < W; y++) {
        for (var x = 0; x < W; x++) {
          var p = y * W + x;
          var dx = x + 0.5 - cx, dy = y + 0.5 - cx;
          var rho = Math.min(Math.sqrt(dx * dx + dy * dy) / cx, 1);
          rhoA[p] = rho;
          var rs = Math.sqrt(Math.max(0, 1 - Math.sqrt(Math.max(0, 1 - rho * rho))));
          kA[p] = rho > 1e-4 ? rs / rho : 0.7071;
          var th = Math.atan2(dy, dx);
          var z = 1 - rho * rho, s2 = Math.sqrt(2 - rho * rho), sinc = rho * s2;
          var u = Math.cos(th), v = -Math.sin(th);
          var phi = Math.asin(clamp(z * Math.sin(PHI0) + v * sinc * Math.cos(PHI0), -1, 1));
          var lam = LAM0 + Math.atan2(u * sinc, Math.cos(PHI0) * z - v * Math.sin(PHI0) * sinc);
          var lat = phi * 180 / Math.PI;
          var lon = ((lam * 180 / Math.PI + 180) % 360 + 360) % 360 - 180;
          var row = Math.floor((90 - lat) * 2);
          rowA[p] = row < 0 ? 0 : row > MASK_H - 1 ? MASK_H - 1 : row;
          var col = Math.floor((lon + 180) * 2);
          colA[p] = col < 0 ? 0 : col > MASK_W - 1 ? MASK_W - 1 : col;
        }
      }
    }

    function atmosphere(e) {
      if (e <= 0.001) return;
      var cx = W / 2;
      if (!atm) {
        atm = ctx.createRadialGradient(cx, cx, cx * 0.84, cx, cx, cx);
        atm.addColorStop(0, "rgba(130,180,230,0)");
        atm.addColorStop(1, "rgba(120,170,225,0.3)");
      }
      ctx.save();
      ctx.beginPath();
      ctx.arc(cx, cx, cx, 0, Math.PI * 2);
      ctx.clip();
      ctx.globalAlpha = Math.min(1, e * 1.1);
      ctx.fillStyle = atm;
      ctx.fillRect(0, 0, W, W);
      ctx.globalAlpha = 1;
      ctx.restore();
    }

    function drawRosette(a) {
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.clearRect(0, 0, W, W);
      ctx.translate(W / 2, W / 2);
      ctx.rotate(a);
      ctx.translate(-W / 2, -W / 2);
      ctx.drawImage(sc, 0, 0, W, W);
      ctx.setTransform(1, 0, 0, 1, 0, 0);
    }

    function drawWarp(tt) {
      var cx = W / 2, e = ease(tt);
      var rot = -(angle0 + SPIN * e);
      var cr = Math.cos(rot), sr = Math.sin(rot);
      var warpCols = (planetSpin * 2) % MASK_W;
      var s = src, o = od;
      for (var y = 0; y < W; y++) {
        var dy = y + 0.5 - cx;
        for (var x = 0; x < W; x++) {
          var p = y * W + x, q = p * 4;
          var dx = x + 0.5 - cx;
          var k = 1 + (kA[p] - 1) * e;
          var sx = cx + (dx * cr - dy * sr) * k;
          var sy = cx + (dx * sr + dy * cr) * k;
          var x0 = sx - 0.5, y0 = sy - 0.5;
          var ix = Math.floor(x0), iy = Math.floor(y0);
          var fx = x0 - ix, fy = y0 - iy;
          var ix1 = ix + 1, iy1 = iy + 1;
          if (ix < 0) ix = 0; else if (ix > W - 1) ix = W - 1;
          if (iy < 0) iy = 0; else if (iy > W - 1) iy = W - 1;
          if (ix1 < 0) ix1 = 0; else if (ix1 > W - 1) ix1 = W - 1;
          if (iy1 < 0) iy1 = 0; else if (iy1 > W - 1) iy1 = W - 1;
          var i00 = (iy * W + ix) * 4, i10 = (iy * W + ix1) * 4, i01 = (iy1 * W + ix) * 4, i11 = (iy1 * W + ix1) * 4;
          var w00 = (1 - fx) * (1 - fy), w10 = fx * (1 - fy), w01 = (1 - fx) * fy, w11 = fx * fy;
          var a = s[i00 + 3] * w00 + s[i10 + 3] * w10 + s[i01 + 3] * w01 + s[i11 + 3] * w11;
          if (a < 1) { o[q] = 0; o[q + 1] = 0; o[q + 2] = 0; o[q + 3] = 0; base[q + 3] = 0; continue; }
          var inv = 255 / a;
          var r = (s[i00] * w00 + s[i10] * w10 + s[i01] * w01 + s[i11] * w11) * inv;
          var g = (s[i00 + 1] * w00 + s[i10 + 1] * w10 + s[i01 + 1] * w01 + s[i11 + 1] * w11) * inv;
          var b = (s[i00 + 2] * w00 + s[i10 + 2] * w10 + s[i01 + 2] * w01 + s[i11 + 2] * w11) * inv;
          var sh = 1 - 0.22 * rhoA[p] * e;
          r *= sh; g *= sh; b *= sh;
          base[q] = r; base[q + 1] = g; base[q + 2] = b; base[q + 3] = a;
          var col = colA[p] + warpCols;
          if (col >= MASK_W) col -= MASK_W;
          var land = landBit(rowA[p], col);
          o[q] = r; o[q + 1] = g; o[q + 2] = b;
          o[q + 3] = land ? a : a * (1 - (1 - OCEAN_A) * e);
        }
      }
      ctx.putImageData(out, 0, 0);
      atmosphere(e);
    }

    function drawPlanet() {
      var scols = (planetSpin * 2) % MASK_W;
      var o = od, bs = base;
      for (var p = 0; p < W * W; p++) {
        var q = p * 4;
        var a = bs[q + 3];
        if (a < 1) { o[q + 3] = 0; continue; }
        var col = colA[p] + scols;
        if (col >= MASK_W) col -= MASK_W;
        var land = landBit(rowA[p], col);
        o[q] = bs[q]; o[q + 1] = bs[q + 1]; o[q + 2] = bs[q + 2];
        o[q + 3] = land ? a : a * OCEAN_A;
      }
      ctx.putImageData(out, 0, 0);
      atmosphere(1);
    }

    function restLoop(now) {
      if (mode !== "rest") { restRaf = 0; return; }
      var dt = (now - restLast) / 1000; restLast = now;
      if (dt > 0.25) dt = 0.25;
      if (visible) { angle += IDLE_RATE * dt; drawRosette(angle); }
      restRaf = requestAnimationFrame(restLoop);
    }

    function morphTick(now) {
      var pr = clamp((now - t0) / dur, 0, 1);
      t = from + (to - from) * pr;
      if (visible) drawWarp(t);
      if (pr < 1) { morphRaf = requestAnimationFrame(morphTick); }
      else {
        morphRaf = 0;
        if (!visible) drawWarp(t);
        if (to === 1) { mode = "planet"; node.classList.add("is-planet"); startPlanet(); }
        else { mode = "rest"; node.classList.remove("is-planet"); angle = angle0; restLast = performance.now(); restRaf = requestAnimationFrame(restLoop); }
      }
    }

    function planetLoop(now) {
      if (mode !== "planet") { planetRaf = 0; return; }
      var dt = (now - planetLast) / 1000; planetLast = now;
      if (dt > 0.25) dt = 0.25;
      if (visible) {
        planetSpin = (planetSpin + PLANET_DEG_PER_SEC * dt) % 360;
        drawPlanet();
      }
      planetRaf = requestAnimationFrame(planetLoop);
    }

    function startPlanet() {
      if (reduced || planetRaf) return;
      planetLast = performance.now(); planetAcc = 1;
      planetRaf = requestAnimationFrame(planetLoop);
    }
    function stopLoops() {
      cancelAnimationFrame(morphRaf); morphRaf = 0;
      cancelAnimationFrame(restRaf); restRaf = 0;
      cancelAnimationFrame(planetRaf); planetRaf = 0;
    }

    function go(target, duration) {
      if (!ready) return;
      clearTimeout(autoTimer);
      stopLoops();
      if (target === 1) planetSpin = 0;
      node.setAttribute("aria-pressed", target === 1 ? "true" : "false");
      if (reduced) {
        t = target; mode = target === 1 ? "planet" : "rest";
        node.classList.toggle("is-planet", target === 1);
        if (target === 1) { angle0 = angle; drawWarp(1); } else { drawRosette(angle); }
        return;
      }
      from = t; to = target; t0 = performance.now(); dur = duration || 1100;
      angle0 = angle; mode = "morph";
      morphRaf = requestAnimationFrame(morphTick);
    }
    function toggle() {
      if (morphRaf) { go(to, 350); return; }
      if (mode === "planet") go(0, 1100);
      else go(1, 1100);
    }
    node.addEventListener("click", function (e) { e.preventDefault(); toggle(); });

    if (window.matchMedia) {
      var mq = window.matchMedia("(prefers-reduced-motion: reduce)");
      var onmq = function () {
        reduced = mq.matches;
        if (reduced) {
          stopLoops();
          if (mode === "morph") {
            t = to;
            if (to === 1) { angle0 = angle; drawWarp(1); mode = "planet"; node.classList.add("is-planet"); }
            else { mode = "rest"; node.classList.remove("is-planet"); drawRosette(angle); }
          }
        } else {
          if (mode === "rest" && !restRaf) { restLast = performance.now(); restRaf = requestAnimationFrame(restLoop); }
          if (mode === "planet" && !planetRaf) startPlanet();
        }
      };
      if (mq.addEventListener) mq.addEventListener("change", onmq);
      else if (mq.addListener) mq.addListener(onmq);
    }

    if ("IntersectionObserver" in window) {
      var io = new IntersectionObserver(function (es) { visible = es[0].isIntersecting; }, { threshold: 0 });
      io.observe(node);
    }

    var bitmap = new Image();
    bitmap.onload = function () {
      sctx.drawImage(bitmap, 0, 0, W, W);
      var id = sctx.getImageData(0, 0, W, W).data;
      for (var i = 0; i < id.length; i += 4) {
        var al = id[i + 3] / 255;
        src[i] = id[i] * al; src[i + 1] = id[i + 1] * al; src[i + 2] = id[i + 2] * al; src[i + 3] = id[i + 3];
      }
      bitmap = null;
      precompute();
      ready = true;
      drawRosette(0);
      node.classList.add("is-ready");
      node.setAttribute("aria-pressed", "false");
      if (reduced) { mode = "rest"; }
      else {
        if (!restRaf) { restLast = performance.now(); restRaf = requestAnimationFrame(restLoop); }
        autoTimer = setTimeout(function () { if (mode === "rest") { go(1, 4600); } }, 1500);
      }
    };
    bitmap.onerror = function () { bitmap = null; };
    bitmap.src = node.getAttribute("data-logo");
  }

  function boot() {
    var nodes = document.querySelectorAll(".logo-morph");
    for (var i = 0; i < nodes.length; i++) init(nodes[i]);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();
